fix: test(): title

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,12 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/bash
 
-npx lint-staged
-npm run check-types
+echo "Running pre-commit hook..."
+
+# Check if the version field has been manually modified
+if git diff -U0 --cached --exit-code package.json | grep -qE 'version'; then
+  echo "ERROR: Modifying the 'version' field in package.json is not allowed."
+  exit 1
+fi
+
+exit 0
+
