fix: check

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -23,9 +23,17 @@ do
     fi
 done
 
-if ! git diff -U0 --cached --exit-code package.json | grep -qE 'version'; then
-  echo "ERROR: You need to update the 'version' field in package.json."
-  exit 1
+# Get the current branch name
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+
+# Check if the branch exists on the remote
+if git ls-remote --exit-code --heads origin $current_branch > /dev/null 2>&1; then
+    echo "Branch $current_branch already exists on remote. Skipping version check."
+    exit 0
+else
+    # Check if version has been updated
+    if ! git diff -U0 --cached --exit-code package.json | grep -qE 'version'; then
+        echo "ERROR: The 'version' field in package.json must be updated."
+        exit 1
+    fi
 fi
-
-
