feat: bla

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -3,14 +3,10 @@
 remote="$1"
 url="$2"
 
+set -x
+
 # Specify your updated branch naming convention regex pattern
-branch_naming_pattern="^refs/heads/#(minor|patch|major)/[a-z0-9-]+$"
-
-if git diff -U0 --cached --exit-code package.json | grep -qE 'version'; then
-  echo "ERROR: Modifying the 'version' field in package.json is not allowed."
-  exit 1
-fi
-
+branch_naming_pattern="^refs/heads/(minor|patch|major)/[a-z0-9-]+$"
 
 while read local_ref local_sha
 do
@@ -24,7 +20,14 @@ do
         exit 0
     else
         # Branch name does not follow the convention
-        echo "Error: Branch name does not follow the naming convention. It should start with '#minor/', '#patch/', or '#major/'."
+        echo "Error: Branch name does not follow the naming convention. It should start with 'minor/', 'patch/', or 'major/'."
         exit 1
     fi
 done
+
+if ! git diff -U0 --cached --exit-code package.json | grep -qE 'version'; then
+  echo "ERROR: You need to update the 'version' field in package.json."
+  exit 1
+fi
+
+
